8.9.0

diff --git a/ubuntu-build/Dockerfile b/ubuntu-build/Dockerfile
--- a/ubuntu-build/Dockerfile
+++ b/ubuntu-build/Dockerfile
@@ -11,7 +11,15 @@ RUN git clone --branch ${CHROMIUM_VERSION} --depth=1 https://chromium.googlesour
 WORKDIR /root/chromium/src
 
 RUN REVERSION=`git rev-parse HEAD` \
-    && gclient sync -r ${REVERSION} --no-history --shallow --auto_rebase --merge --no_bootstrap
+    && (gclient sync -r ${REVERSION} --no-history --shallow --auto_rebase --merge --no_bootstrap -v -v) || echo 'ignore error'
+
+RUN git config --global user.email "git@microbox.com" \
+    && git config --global user.name "Microbox" \
+    && cd third_party/webrtc \
+    && git fetch origin a2329acf18dc0653106782f63f54675dab9c483e
+
+RUN gclient sync -r ${REVERSION} --no-history --shallow --auto_rebase --merge --no_bootstrap -v -v
+
 #RUN gclient sync -r ${CHROMIUM_VERSION} --no-history --reset --shallow --nohooks
 #RUN gclient runhooks
 RUN ./build/install-build-deps.sh --no-prompt
